# Minimal example using a linked biblatex bibliography file.
* Using linked bibliography files

If you prefer using a single global bibliography bibtex (.bib) file but still want to use a local file name for the =\addbibresource= path, you can use a symbolic link from the global file to a local file name in the same directory as the org file which is being rendered.  =\addbibresource= works also with linked files as source.

* Ελληνικά
I doubt that there is any useful information here\nobreakspace\cite{wikibook}.

All we know is limited, apart from knowing the answer we all know. Or do we? Wombat and Koala have discovered some interesting things\nobreakspace\cite{wombat2016}.

Some people are too nosy. What can happen to them is described by Laura Lion\nobreakspace\cite[9]{lion2010}.

Ελληνικά.

*Ελληνικά.*

/Ελληνικά./

* 日本語

日本語。

*日本語。*

/日本語。/

* COMMENT latex-header

#+BEGIN_SRC latex
  \documentclass{article}
  \usepackage{xeCJK}
  \setmainfont{Times New Roman}
  \setCJKmainfont[BoldFont=STHeiti,ItalicFont=STKaiti]{STSong}
  \usepackage{biblatex}
  \addbibresource{bibliography-LINKED.bib}
  \begin{document}
#+END_SRC
* COMMENT latex-footer

#+BEGIN_SRC latex
\printbibliography
\end{document}
#+END_SRC
