# Minimal multilingual example both for body and for bibliography.
* Multilingual text in body and bibliography

This example uses =xelatex= to render english, greek and japanese text.  As main font (for latin and greek) it uses =Linux Libertine O=[fn::The Linux Libertine O font is better than Times New Roman.], and for Japanese it uses =STSong=, with =STHeiti= for bold and =STKaiti= for italics.  For japanese, it uses the command =setCJKmainfont= combined with the package =xeCJK=.  The =xeCJK= package recognizes japanese text and switches to =CJKmainfont= automatically. Thus, there is no need to insert any LaTeX commands for distinguishing english, greek or japanese text since the =xeCJK= package distinguishes these by itself in the background.

This setting is valid for rendering both the main text of the file (the present text) and the bibliography section.  This means that both the main text and the bibliography may contain english, greek and japanese text.
* Chicago Bibliography

This document uses the =biblatex-chicago= package with options: =authordate=, =autocite=inline= *but without the =natbib= option*.

** About  Bibliography Sorting

This example contains an edge case in bibliography sorting:  The "wikibook" citation refers to a bibtex entry which  does not have an author. In the absense of an "author" key, this entry is sorted by the "organization" key instead.

* Ελληνικά
I doubt that there is any useful information here \parencite{wikibook}.

All we know is limited, apart from knowing the answer we all know. Or do we? Wombat and Koala have discovered some interesting things \parencite{wombat2016}.

Some people are too nosy. What can happen to them is described by Laura Lion \parencite[9]{lion2010}.

Ελληνικά.

*Ελληνικά.*

/Ελληνικά./

* 日本語

日本語。

*日本語。*

/日本語。/

* COMMENT latex-header

#+BEGIN_SRC latex
  \usepackage{xeCJK}
  \setmainfont{Linux Libertine O} % {Times New Roman}
  \setCJKmainfont[BoldFont=STHeiti,ItalicFont=STKaiti]{STSong}
  \usepackage[authordate,autocite=inline,backend=biber]{biblatex-chicago}
  \bibliography{bibliography-ml.bib}

  \begin{document}
#+END_SRC
* COMMENT latex-footer

#+BEGIN_SRC latex
\printbibliography
\end{document}
#+END_SRC
