Started: January 2016

* Requirements: Prelude

This library is the contents of the =personal= folder for configuring emacs when using the [[https://github.com/bbatsov/prelude][prelude]] library for EMACS by bbatsov Bozhidar Batsov.

The path for this folder for a standard installation of EMACS should be:

: ~/.emacs.d/personal

* Some packages used

Before installing my setup, have a look at the following list of packages used, and my =prelude-modules.el= configuration.  Install prelude modules and the packages listed below to prevent having to restart emacs many times because of missing packages.

Following is an *incomplete* list of the packages used.  Some of these come with prelude, others have to be downloaded with =package-install=, others still (e.g. =ag=) must be installed from the shell command line. 

Also: Have a look at ~/emacs.d/sample/prelude-modules.el and copy it to ~/.emacs.d/ then edit it to customize.  These are the prelude modules that I use in my =prelude-modules.el=:

1. (require 'prelude-helm) ;; Interface for narrowing and search
2. (require 'prelude-helm-everywhere) ;; Enable Helm everywhere
3. (require 'prelude-key-chord) ;; Binds useful features to key combinations
4. (require 'prelude-emacs-lisp)
5. (require 'prelude-org)

Here are the packages that I recall using a lot: 

1. projectile (included in prelude)
2. helm (helm-everywhere) (installed with prelude-modules.el)
3. key-chord-mode (installed with prelude-modules.el)
4. ace
5. ace-isearch
6. evil-mode (for moving in buffer instead of ace when input mode is greek)
7. evil-org (like for evil-mode, but in org files)
8. linum-mode
9. linum-relative-mode
10. helm-swoop (required by ace-isearch)
11. paredit
12. hl-sexp
13. rainbow-identifiers
14. ag (for projectile and helm-projectile, is a unix package, installed via shell)
15. calfw
16. org-calfw (indispensable)
17. moe theme
18. deft
19. dired+
20. bookmark+
21. elisp-slime-nav https://github.com/purcell/elisp-slime-nav
22. hs-minor-mode (hide-show blocks of code)
23. ox-twbs Org-export twitter-bootstrap

I am evaluating =company=.

I do not use =yasnippet= - but am thinking of trying it out again.

My current versions of org-notes and org-pm (not org-pm2) use =grizzl=, but I am in the process of substituting this by =helm=.

* Installation

** 1: Download this library
Get this library by running this command on a shell terminal:

#+BEGIN_SRC sh
git clone --recursive https://github.com/iani/emacs-prelude-personal.git
#+END_SRC

This will create a folder emacs-prelude-personal at the location where you ran the command. 

** 2: Link the folder of this library to your .emacs.d folder

Then link the library to your prelude personal folder by running the following commands. 

*Take care to edit* =/full/path/to= *to correspond to the actual location of* =emacs-prelude-personal= *as you downloaded it with* =git -clone=.

#+BEGIN_SRC sh
# Rename previous personal folder to personal + current date and time:
mv ~/.emacs.d/personal ~/.emacs.d/"personal-`date`"
# link downloaded library to personal folder: 
ln -s /full/path/to/emacs-prelude-personal ~/.emacs.d/personal
#+END_SRC

** 3. Restart emacs

* Keyboard commands

** general
 | Hyper-m | air-menu: files, agenda, hydra |
 | Hyper-M | latex, sc-lang/server/utils    |

** sclang mode only

| Hyper-s | snippet hydra             |
| C-h C-s | snippet hydra             |
| C-h g   | various guis (incomplete) |


