(TeX-add-style-hook
 "LAC-19"
 (lambda ()
   (TeX-add-symbols
    "plainheadrulewidth"
    "plainfootrulewidth"
    "headwidth"
    "ninept"
    "normalsize"
    "thefootnote"
    "maketitle"
    "title"
    "thanks"
    "sthanks"
    "affiliationSpace"
    "affiliation"
    "affiliations"
    "twoaffiliations"
    "threeaffiliations"
    "fouraffiliations"
    "copyrightnotice"
    "toappear"
    "newblock"
    "lhead"
    "chead"
    "rhead"
    "lfoot"
    "cfoot"
    "rfoot"
    "fancyplain"
    "baselinestretch"
    "headrule"
    "headrulewidth"
    "footrule"
    "footrulewidth"
    "subsectionmark"
    "chaptermark"
    "sectionmark"
    "topfloat"
    "botfloat"
    "iftopfloat"
    "ifbotfloat"
    "iffloatpage")
   (LaTeX-add-environments
    "thebibliography"
    "abstract")
   (LaTeX-add-pagestyles
    "preprint"
    "empty"
    "fancy"
    "fancyplain"
    "plain"))
 :latex)

