# enable using smc2018 template in org mode

#+BEGIN_EXPORT latex
\begin{abstract}
This is an org-mode port of the LaTeX template for paper submissions
to SMC2018.  It should be compiled with \textit{pdflatex} (it does not
compile with XeLaTeX).

Note: The present abstract was written inside a \texttt{\#\+BEGIN\_EXPORT latex} babel block.

To set the title, edit the contents of the \texttt{\textbackslash{}def\textbackslash{}papertitle\{\}}
user variable.  To set the authors, edit the contents of the
\texttt{\textbackslash{}def\textbackslash{}firstauthor} etc. variables and to set the credits,
uncomment and edit one of the sections \texttt{\textbackslash{}oneauthor},
\texttt{\textbackslash{}twoauthors} or \texttt{\textbackslash{}threeauthors} according to the case.  Other parts such as figures, tables, can be created by inserting the raw LaTeX commands - see examples in original smc2018template.tex.  Footnotes can be added using the standard org-mode footnote mechanism.
\end{abstract}
#+END_EXPORT

* Instructions for use with org-mode

** pdflatex, Title, Authors
This is an org-mode port of the LaTeX template for paper submissions to SMC2018.  It should be compiled with /pdflatex/ (it does not compile with /XeLaTeX/).  To set the title, edit the contents of the =\def\papertitle{}= user variable.  To set the authors, edit the contents of the =\def\firstauthor= etc. variables and to set the credits, uncomment and edit one of the sections =\oneauthor=, =\twoauthors= or =\threeauthors=, depending on the number of authors.  Other parts such as figures, tables, can be created by inserting the raw LaTeX commands.  An example of including a figure is included in the present document.  

** Write Footnotes using org-mode format

Footnotes can be coded using the methods provided by org-mode[fn::For example, this is a footnote.].
 
However, there should not be a section named "Footnotes", because it is ignored by the exporter.

** Include Figures using LaTeX format

To include figures, use plain latex inside org-mode, as shown in the following example. This is a test of a figure (see Fig. \ref{fig:example}):

\begin{figure}[t]
\centering
\includegraphics[width=0.6\columnwidth]{figure}
\caption{Figure captions should be placed below the figure, 
exactly like this.\label{fig:example}}
\end{figure}

** Write Citations using LaTeX citation format

This is a dummy section.  It also contains a citation: \cite{Someone:00}

*** Subsubsection example.

This is a dummy subsubsection containing a second citation: \cite{Someone:09}

** Limitations: Unnumbered Sections
 There are important limitations in using the /smc2018 template/ to export a paper from source written in org-mode:

 /Unnumbered/ sections (LaTeX: =\section*{Section Name}=) can be defined in org-mode by setting the =UNNUMBERED= property of a section to =t=.  However, this template produces headlines that are in a slightly larger font than the section headlines of the same level and are not automatically capitalized[fn::Unfortunately, I could not fix the /.sty/ template to correct this problem.]. Thus, for unnumbered sections such as /Abstract/ or /Acknowledgments/, one must use the LaTeX code (=begin{abstract}= - =end{abstract}=) to enclose the section.  When one does this, any org-mode specific formatting in the source enclosed within the begin/end section is not exported properly.  Thus, if any formatting or special characters (e.g. #, \, etc.) are used, one must write these in LaTeX encoding.  It is suggested to write such sections inside =#+BEGIN_EXPORT latex= blocks, because one can then open the block in LaTeX mode and use the LaTeX formatting shortcuts provided by EMACS. 

* TEST Unnumbered SECTION
  :PROPERTIES:
  :UNNUMBERED: t
  :END:

Compare the size of the heading when the section is unnumbered.

* COMMENT latex-header

#+BEGIN_SRC latex
\documentclass{article}
\usepackage{smc2018}
\usepackage{times}
\usepackage{ifpdf}
\usepackage[english]{babel}
% \usepackage{cite}
\usepackage[backend=biber]{biblatex}
\addbibresource{smc2018bib.bib}
%%%%%%%%%%%%%%%%%%%%%%%% Some useful packages %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%% See related documentation %%%%%%%%%%%%%%%%%%%%%%%%%%
%\usepackage{amsmath} % popular packages from Am. Math. Soc. Please use the 
%\usepackage{amssymb} % related math environments (split, subequation, cases,
%\usepackage{amsfonts}% multline, etc.)
%\usepackage{bm}      % Bold Math package, defines the command \bf{}
%\usepackage{paralist}% extended list environments
%%subfig.sty is the modern replacement for subfigure.sty. However, subfig.sty 
%%requires and automatically loads caption.sty which overrides class handling 
%%of captions. To prevent this problem, preload caption.sty with caption=false 
%\usepackage[caption=false]{caption}
%\usepackage[font=footnotesize]{subfig}

%user defined variables
\def\papertitle{ORG-MODE TEMPLATE FOR SMC2018}
\def\firstauthor{First author}
\def\secondauthor{Second author}
\def\thirdauthor{Third author}

% adds the automatic
% Saves a lot of output space in PDF... after conversion with the distiller
% Delete if you cannot get PS fonts working on your system.

% pdf-tex settings: detect automatically if run by latex or pdflatex
\newif\ifpdf
\ifx\pdfoutput\relax
\else
   \ifcase\pdfoutput
      \pdffalse
   \else
      \pdftrue
\fi

\ifpdf % compiling with pdflatex
  \usepackage[pdftex,
    pdftitle={\papertitle},
    pdfauthor={\firstauthor, \secondauthor, \thirdauthor},
    bookmarksnumbered, % use section numbers with bookmarks
    pdfstartview=XYZ % start with zoom=100% instead of full screen; 
                     % especially useful if working with a big screen :-)
   ]{hyperref}
  %\pdfcompresslevel=9

  \usepackage[pdftex]{graphicx}
  % declare the path(s) where your graphic files are and their extensions so 
  %you won't have to specify these with every instance of \includegraphics
  \graphicspath{{./figures/}}
  \DeclareGraphicsExtensions{.pdf,.jpeg,.png}

  \usepackage[figure,table]{hypcap}

\else % compiling with latex
  \usepackage[dvips,
    bookmarksnumbered, % use section numbers with bookmarks
    pdfstartview=XYZ % start with zoom=100% instead of full screen
  ]{hyperref}  % hyperrefs are active in the pdf file after conversion

  \usepackage[dvips]{epsfig,graphicx}
  % declare the path(s) where your graphic files are and their extensions so 
  %you won't have to specify these with every instance of \includegraphics
  \graphicspath{{./figures/}}
  \DeclareGraphicsExtensions{.eps}

  \usepackage[figure,table]{hypcap}
\fi

%setup the hyperref package - make the links black without a surrounding frame
\hypersetup{
    colorlinks,%
    citecolor=black,%
    filecolor=black,%
    linkcolor=black,%
    urlcolor=black
}


% Title.
% ------
\title{\papertitle}

% Authors
% Please note that submissions are NOT anonymous, therefore 
% authors' names have to be VISIBLE in your manuscript. 
%
% Single address
% To use with only one author or several with the same address
% ---------------
%\oneauthor
%   {\firstauthor} {Affiliation1 \\ %
%     {\tt \href{mailto:author1@smcnetwork.org}{author1@smcnetwork.org}}}

%Two addresses
%--------------
% \twoauthors
%   {\firstauthor} {Affiliation1 \\ %
%     {\tt \href{mailto:author1@smcnetwork.org}{author1@smcnetwork.org}}}
%   {\secondauthor} {Affiliation2 \\ %
%     {\tt \href{mailto:author2@smcnetwork.org}{author2@smcnetwork.org}}}

% Three addresses
% --------------
 \threeauthors
   {\firstauthor} {Affiliation1 \\ %
     {\tt \href{mailto:author1@smcnetwork.org}{author1@smcnetwork.org}}}
   {\secondauthor} {Affiliation2 \\ %
     {\tt \href{mailto:author2@smcnetwork.org}{author2@smcnetwork.org}}}
   {\thirdauthor} { Affiliation3 \\ %
     {\tt \href{mailto:author3@smcnetwork.org}{author3@smcnetwork.org}}}


% ***************************************** the document starts here ***************
\begin{document}
%
\capstartfalse
\maketitle
\capstarttrue
#+END_SRC
* COMMENT latex-footer

#+BEGIN_SRC latex
\printbibliography
\end{document}
#+END_SRC
