

I doubt that there is any useful information here\textasciitilde{}\cite{wikibook}. (Note: This was =\cite=).

All we know is limited, apart from knowing the answer we all know. Or do we? Wombat and Koala have discovered some interesting things\textasciitilde{}\parencite{wombat2016}. (Note: This was =\parencite=).

Some people are too nosy. What can happen to them is described by Laura Lion\textasciitilde{}\parencite[9]{lion2010}. (Note: This was =\parencite=).

*Observation* When using the default bibliography style, which is /numbered/, there seems to be no difference between =\parencite= and =\cite=.  These two differ when using /author-date/ citation style. 

*N.B. The file containing the bibliography data in bibtex, =bibliography.bib=, should be located in the same folder as the org-file being compiled.  Otherwise, the path to the file should be given either in absolute or relative format.*

_Creating a symbolic link to the bibliography databse file does not work.  The actual file has to be found in the path indicated by =\addbibresource{...}=_

* COMMENT latex-header

#+BEGIN_SRC latex
  \documentclass{article}
  \usepackage{xeCJK}
  \setmainfont{Times}
  \setCJKmainfont[BoldFont=STHeiti,ItalicFont=STKaiti]{STSong}
  \usepackage{biblatex}
  % Note: the file bibliography.bib should be in the same directory
  % as the org file that you want to convert with latex:
  \addbibresource{bibliography.bib}
  \begin{document}
#+END_SRC

* COMMENT latex-footer

#+BEGIN_SRC latex
\printbibliography
\end{document}
#+END_SRC
