To export an org mode file containing texts with non-latin character sets (greek or other), you need to use an alternative latex processor such as xelatex.  The present file explains how to do this with org-mode version 9 or greater.  Due to incompatibilities between org-mode versions 8 to 9, please follow the instructions here, otherwise export with xelatex may be broken partly or entirely.

* Setting up org-mode for multilingual export in latex with OS native fonts
  :PROPERTIES:
  :DATE:     <2018-03-06 Tue 10:38>
  :END:

N.B. Xelatex enables one to use system fonts. These are necessary for languages such as greek, which requires a character set other than latin.  
The present section tells org mode to use xelatex.  However this only works for org-version 9 or greater.  Use command =org-version= to find out which version is installed.  To upgrade to version 9 follow these steps: 

**  Delete default org code base

 Delete the current or default org version code.  In macOS this is found inside the Emacs.app folder at this location: Emacs.app/Contents/Resources/lisp/org  It is necessary to delete this entire folder before upgrading, because if you keep it, it will cause conflicts with version 9 which will either disable latex export or result in errors when definin properties such as =#+TITLE:=, =#+AUTHOR:=, =#+DATE:= in an org file. 

** Add org-mode repository to the emacs-lisp package list variable

 Run the following code: 

 #+BEGIN_SRC elisp
 (setq package-archives
       '(("melpa" . "https://melpa.org/packages/")
         ("gnu" . "https://elpa.gnu.org/packages/")
         ("org" . "http://orgmode.org/elpa/")))
 (package-initialize)
 #+END_SRC

 
**  Install the org-plus-contrib package either with command =package-install= or with =package-list-packages= and then searching =org-plus-contrib=, then typing i to mark it for installation and then typing x to install the marked packages.
